---
- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no

  tasks:
    - name: be sure xvfb is installed
      apt: name=xvfb state=installed
      sudo: yes

    - name: be sure xvfb bg setting is written
      lineinfile: create=yes dest=~/.zprofile state=present regexp='^(\s*)Xvfb :1 -screen 0 1024x768x24 &$' line='Xvfb :1 -screen 0 1024x768x24 &'
