---
- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no

  tasks:
    - name: be sure xvfb is installed
      apt: name=xvfb state=installed
      sudo: yes

    - name: be sure xvfb profile
      shell: echo 'Xvfb :1 -screen 0 1024x768x24 &' > /etc/profile.d/xvfb.sh creates=/etc/profile.d/xvfb.sh
      sudo: yes
